# Generated by Django 2.2.5 on 2019-09-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='merchant_description',
            field=models.CharField(default='input merchant description', max_length=200),
        ),
    ]
