# Generated by Django 2.2.5 on 2019-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0002_auto_20190926_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
