# Generated by Django 2.2.5 on 2019-09-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0003_auto_20190925_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchants',
            old_name='admin',
            new_name='user_profile',
        ),
    ]
