# Generated by Django 2.2.5 on 2019-09-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0004_auto_20190925_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='property',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='merchant',
            new_name='merchant_id',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='property_type',
            new_name='property_type_id',
        ),
        migrations.RenameField(
            model_name='propertytype',
            old_name='merchant',
            new_name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='merchants',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='merchants',
            name='admin_id',
            field=models.ForeignKey(db_column='admin_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='epa_frontend.Profile'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='epa_frontend.Properties'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to='epa_frontend.Profile'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='merchant_id',
            field=models.ForeignKey(db_column='merchant_id', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_details', to='epa_frontend.Merchants'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type_id',
            field=models.ForeignKey(db_column='property_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='property_type_information', to='epa_frontend.PropertyType'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='merchant_id',
            field=models.ForeignKey(db_column='merchant_id', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_information', to='epa_frontend.Merchants'),
        ),
    ]
