# Generated by Django 2.2.5 on 2019-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0004_auto_20190926_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
