# Generated by Django 2.2.10 on 2020-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0006_auto_20200317_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
