# Generated by Django 2.2.10 on 2020-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0007_events_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['created_at', 'is_featured', 'is_recommended']},
        ),
        migrations.AddField(
            model_name='events',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
