# Generated by Django 2.2.10 on 2020-03-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0009_auto_20200317_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='images',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
