# Generated by Django 2.2.10 on 2020-03-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_frontend', '0010_auto_20200317_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_id',
        ),
        migrations.AddField(
            model_name='events',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
